### ISSUE TITLE
stderr : error.txt

### ISSUE THREAD

**Issue by sxmeer-ahmed** [SajidZakaria/ST3-CP-Environment#1]
Can you also add stderr or error.txt file in it? sometimes I have to check where is my code is wrong so I want that output too.

**Comment by SajidZakaria** [comment]
Sorry, this build does not focus on this. And I suppose it would make it a bit more complicated, and I can not afford the time as I'm not actively working on this project anymore. Might add this if I have another major update or bug fix.
